numSpec = 4
dt = 1
tau = 1
minBW = [12, 40, 20, 82]
maxBW = [12, 40, 20, 82]
spectRange = [1900, 300, 1300, 500]
spectPower = [4,1,4,10]
epsilon = 0.5
t_sd = 0.1
t_td = 1
idle_channel_prob = 1
switching_energy = 0.0001
sensing_power = 0.00004
lambda_val = 1
messageBurst = [2, 5]

minTTL=15
maxTau = 1
default_num_channels = 10
M = [2, 20, 40, 60]
packet_size = 5
active_channel_prob = 1
T = 480
V = 24
NoOfSources = 3
NoOfDataCenters = 3
S = [0, 1, 2, 3]
max_nodes = 30
StartTime = 1
debug_message = 257
dataset = "Lexington"
generate_link_exists = False
generate_messages = True
num_messages = 206
DataMule_path = 'DataMules/Lexington/50/1/'
path_to_folder = 'DataMules/Lexington/50/1/Link_Exists/LE_1_480/XChant_ALL/mules_24/channels_6/P_users_150'
path_to_metrics = 'DataMules/Lexington/50/1/Link_Exists/LE_1_480/XChant_ALL/mules_24/channels_6/P_users_150/msgfile_1_15/puserfile_0/TTL_60/BuffSize_-1/numTransceivers_1/'
pkl_folder = 'Day1_pkl/'
path_to_LLC = 'DataMules/Lexington/50/1/Link_Exists/LE_1_480/'
num_replicas = 1
limited_time_to_transfer = True
restrict_band_access = False
restrict_channel_access = True
priority_queue = False
broadcast = False
geographical_routing = False
num_nodes_to_fwd = -1
generate_new_primary_users = False
num_channels = 6
num_primary_users = 150
path_to_save_LLC = 'DataMules/Lexington/50/1/Link_Exists/LE_1_480/'
puser_round = 0
TTL = 60
max_packets_in_buffer = -1
num_transceivers = 1
num_sec_per_tau = 1
link_exists_folder = 'DataMules/Lexington/50/1/Link_Exists/LE_1_480/'
delivered_file = 'delivered_messages.txt'
consumed_energy_file = 'energy_metrics.txt'
not_delivered_file = 'not_delivered.txt'
generated_messages_file = 'Generated_Messages/mean15/generated_messages1.txt'

metrics_file = 'metrics.txt'
packet_delivered_file = 'packets_delivered.txt'
protocol = 'XChant'
smart_setting = 'optimistic'
debug_mode = -1
overhead_file = 'overhead.txt'
metric_interval = 30

VMIN = 135
VMAX = 400
wait_time = [2,7]
route_start_time1 = 0
route_start_time2 = 5
lex_data_directory = 'Lexington/'
day_num = 1
